var guerrero = {
    "level1":{
      "primerAtaque":1,
      "salvaFort":2,
      "salvaRefle":0, 
      "salvaVolun":0 
    },
    "level2":{
      "primerAtaque":2,
      "salvaFort":3,
      "salvaRefle":0, 
      "salvaVolun":0 
    },
    "level3":{
      "primerAtaque":3,
      "salvaFort":3,
      "salvaRefle":1, 
      "salvaVolun":1 
    },
    "level4":{
      "primerAtaque":4,
      "salvaFort":4,
      "salvaRefle":1, 
      "salvaVolun":1 
    },
    "level5":{
      "primerAtaque":5,
      "salvaFort":4,
      "salvaRefle":1, 
      "salvaVolun":1 
    },
    "level6":{
      "primerAtaque":6,
      "segundoAtaque":1,
      "salvaFort":5,
      "salvaRefle":2, 
      "salvaVolun":2 
    },
    "level7":{
      "primerAtaque":7,
      "segundoAtaque":2,
      "salvaFort":5,
      "salvaRefle":2, 
      "salvaVolun":2 
    },
    "level8":{
      "primerAtaque":8,
      "segundoAtaque":3,
      "salvaFort":6,
      "salvaRefle":2, 
      "salvaVolun":2 
    },
    "level9":{
      "primerAtaque":9,
      "segundoAtaque":4,
      "salvaFort":6,
      "salvaRefle":3, 
      "salvaVolun":3 
    },
    "level10":{
      "primerAtaque":10,
      "segundoAtaque":5,
      "salvaFort":7,
      "salvaRefle":3, 
      "salvaVolun":3 
    },
    "level11":{
      "primerAtaque":11,
      "segundoAtaque":6,
      "tercerAtaque":1,
      "salvaFort":7,
      "salvaRefle":3, 
      "salvaVolun":3 
    },
    "level12":{
      "primerAtaque":12,
      "segundoAtaque":7,
      "tercerAtaque":2,
      "salvaFort":8,
      "salvaRefle":4, 
      "salvaVolun":4 
    },
    "level13":{
      "primerAtaque":13,
      "segundoAtaque":8,
      "tercerAtaque":3,
      "salvaFort":8,
      "salvaRefle":4, 
      "salvaVolun":4 
    },
    "level14":{
      "primerAtaque":14,
      "segundoAtaque":9,
      "tercerAtaque":4,
      "salvaFort":9,
      "salvaRefle":4, 
      "salvaVolun":4 
    },
    "level15":{
      "primerAtaque":15,
      "segundoAtaque":10,
      "tercerAtaque":5,
      "salvaFort":9,
      "salvaRefle":5, 
      "salvaVolun":5 
    },
    "level16":{
      "primerAtaque":16,
      "segundoAtaque":11,
      "tercerAtaque":6,
      "cuartoAtaque":1,
      "salvaFort":10,
      "salvaRefle":5, 
      "salvaVolun":5 
    },
    "level17":{
      "primerAtaque":17,
      "segundoAtaque":12,
      "tercerAtaque":7,
      "cuartoAtaque":2,
      "salvaFort":10,
      "salvaRefle":5, 
      "salvaVolun":5 
    },
    "level18":{
      "primerAtaque":18,
      "segundoAtaque":13,
      "tercerAtaque":8,
      "cuartoAtaque":3,
      "salvaFort":11,
      "salvaRefle":6, 
      "salvaVolun":6 
    },
    "level19":{
      "primerAtaque":19,
      "segundoAtaque":14,
      "tercerAtaque":9,
      "cuartoAtaque":4,
      "salvaFort":11,
      "salvaRefle":6, 
      "salvaVolun":6 
    },
    "level20":{
      "primerAtaque":20,
      "segundoAtaque":15,
      "tercerAtaque":10,
      "cuartoAtaque":5,
      "salvaFort":12,
      "salvaRefle":6, 
      "salvaVolun":6 
    },
}

var guerrero2= {
  "primerAtaque":nivel=>nivel, 
  "segundoAtaque":15,
  "tercerAtaque":10,
  "cuartoAtaque":5,
  "salvaFort":12,
  "salvaRefle":6, 
  "salvaVolun":6 
};






